# Generated by Django 4.2 on 2023-04-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='grtnak', verbose_name='Home image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='homename',
            options={'ordering': ['-id']},
        ),
    ]
