# Generated by Django 4.2 on 2023-04-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='About name'),
        ),
        migrations.AddField(
            model_name='about',
            name='name_hy',
            field=models.CharField(max_length=60, null=True, verbose_name='About name'),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='About name'),
        ),
        migrations.AddField(
            model_name='about',
            name='text_en',
            field=models.TextField(null=True, verbose_name='About text'),
        ),
        migrations.AddField(
            model_name='about',
            name='text_hy',
            field=models.TextField(null=True, verbose_name='About text'),
        ),
        migrations.AddField(
            model_name='about',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='About text'),
        ),
    ]
