# Generated by Django 4.2 on 2023-04-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about_name_en_about_name_hy_about_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('img', models.ImageField(upload_to='products', verbose_name='Product image')),
                ('price', models.PositiveIntegerField(verbose_name='Product price')),
                ('compound', models.TextField(verbose_name='Product compound')),
            ],
        ),
    ]
